### ISSUE TITLE
Error while deserializing

### ISSUE THREAD

**Issue by azrael1111** [csharpsi/webmerge.net#10]
Hy, 

I'm trying to get a list of all documents and the response deserialization is raising an exception.

![image](https://cloud.githubusercontent.com/assets/3955371/20940052/98dd5170-bbf1-11e6-8253-0853366f0061.png)

**Comment by csharpsi** [comment]
Hi @azrael1111 

This looks like a change to the API - I'll take a look and get back to you

**Comment by csharpsi** [comment]
OK, I've made a change to the `Document` class which changes the `SizeWidth` and `SizeHeight` types from `double?` to `string`, which is what is actually returned from the API. This should fix your issue.

You can get this by updating your nuget package to version >= 2.0.26

**Comment by azrael1111** [comment]
thanks
